### ISSUE TITLE
Make an About page

### ISSUE THREAD

**Issue by SteveChenDC** [CodeandCoffeeCommunity/nyccodecoffee-website#3]

**Comment by DorianCBrwn** [comment]
I shall take on this challenge lol

**Comment by SteveChenDC** [comment]
@DorianCBrwn the copy! Let me know if I can help on the design or if you have anything in mind.

https://docs.google.com/document/d/1iJUk8hM8SSPwDFgpnNyY7mEHp5h9GyuR9A36IaYboIY/edit?usp=sharing
