### ISSUE TITLE
Add social media icons on header

### ISSUE THREAD

**Issue by juliafmorgado** [CodeandCoffeeCommunity/nyccodecoffee-website#5]
Add twitter, instagram and linkedin icons on header

**Comment by shubhamsigdar1** [comment]
Julia, i want to contribute to this project...Where do you want to add Twitter, Instagram, and LinkedIn icons on which side

**Comment by shubhamsinghbundela** [comment]
Julia, I want to contribute on this project

**Comment by juliafmorgado** [comment]
Hey Shubham,

The goal is to have those icons to the right of "Code of conduct" 

![Screen Shot 2022-07-16 at 9 20 01 AM](https://user-images.githubusercontent.com/52685951/179356671-fbce592a-9b13-4f55-96bf-c17ff6a33501.png)

**Comment by shubhamsinghbundela** [comment]
ok Julia
